#!/usr/bin/env fish

# List all files that are ignored inside the current repo

# TODO(vipa, 2023-02-22): This is slow, but "obviously" correct, would
# be nice to use something more direct for the systems that support it

comm -1 -3 (sd repo files | sort | psub) (find ./* -type f | sed 's#^./##' | sort | psub)
